apiVersion: vendir.k14s.io/v1alpha1
kind: Config
# require a user to use at least version 0.18.0 of vendir
minimumRequiredVersion: 0.18.0
directories:

  # this path is the top level directory to place retrieved assets
  # - path: deploy/synced/manifests
  #   contents:
  #     - path: loki-stack
  #       helmChart:
  #         # which Helm repository to find the desired Helm chart
  #         repository:
  #           url: https://grafana.github.io/helm-charts
  #         # the name of the desired Helm chart in the above repository
  #         name: loki-stack
  #         # the specific version of the above Helm chart
  #         version: 2.3.1

  # This path syncs HELM CHARTS ONLY
  - path: deploy/synced/helm-charts
    contents:
      - path: argo-workflows
        helmChart:
          # which Helm repository to find the desired Helm chart
          repository:
            url: https://charts.bitnami.com/bitnami
          # the name of the desired Helm chart in the above repository
          name: argo-workflows
          # the specific version of the above Helm chart
          version: 0.1.13

      - path: argo-cd
        helmChart:
          # which Helm repository to find the desired Helm chart
          repository:
            url: https://charts.bitnami.com/bitnami
          # the name of the desired Helm chart in the above repository
          name: argo-cd
          # the specific version of the above Helm chart
          version: 2.0.19

      - path: argocd-notifications
        helmChart:
          # which Helm repository to find the desired Helm chart
          repository:
            url: https://argoproj.github.io/argo-helm
          # the name of the desired Helm chart in the above repository
          name: argocd-notifications
          # the specific version of the above Helm chart
          version: 1.6.1

      - path: argocd-applicationset
        helmChart:
          # which Helm repository to find the desired Helm chart
          repository:
            url: https://argoproj.github.io/argo-helm
          # the name of the desired Helm chart in the above repository
          name: argocd-applicationset
          # the specific version of the above Helm chart
          version: 1.7.0

      - path: argo-rollouts
        helmChart:
          # which Helm repository to find the desired Helm chart
          repository:
            url: https://argoproj.github.io/argo-helm
          # the name of the desired Helm chart in the above repository
          name: argo-rollouts
          # the specific version of the above Helm chart
          version: 2.6.0

      - path: argo-events
        helmChart:
          # which Helm repository to find the desired Helm chart
          repository:
            url: https://argoproj.github.io/argo-helm
          # the name of the desired Helm chart in the above repository
          name: argo-rollouts
          # the specific version of the above Helm chart
          version: 2.6.0

      # - path: nginx
      #   # retrieve from a Git repostiory
      #   git:
      #     # the path to a valid Git repository
      #     url: https://github.com/ktsakalozos/SimpleProject
      #     # ref can be a branch, tag, or commit SHA
      #     ref: master
      #   # by default all files are fetched, but we only want the
      #   # `deployment.yaml` file, so let vendir know
      #   includePaths:
      #     - deploy/nginx.yaml
      #   # by default, vendir would download the above included path to
      #   # `deploy/synced/nginx/content/en/examples/application/deployment.yaml`,
      #   # but we'd prefer to have `deploy/synced/nginx/deployment.yaml`, which
      #   # we can have by specifying `newRootPath`
        # newRootPath: content/en/examples/application/
