apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.2.0/manifests/install.yaml
  - https://raw.githubusercontent.com/argoproj-labs/applicationset/v0.2.0/manifests/install.yaml

configMapGenerator:

  - name: argocd-cm
    behavior: merge
    literals:
      - "timeout.reconciliation=15s"

# This is only good for local setups.
  - name: argocd-cmd-params-cm
    behavior: merge
    literals:
      - "server.disable.auth=true"  # This is bad, must figure this out...
      - "server.insecure=true"
      - "server.basehref=/argocd"
      - "server.rootpath=/argocd"
      - "server.staticassets=/shared/app"
      # - "server.ingress.hosts=kubernetes.docker.internal"

patches:
  # reconfigure argo to expose 7070
  - target:
      name: argocd-server
      version: v1
      kind: Service
    patch: |-
      - op: replace
        path: /spec/ports/0/port
        value: 7070
